### ISSUE TITLE
bug: executing the localBuildRun scripts multiple times creates the tutorials repository twice in build/playbooks

### ISSUE THREAD

**Issue by GuentherJulian** [devonfw-tutorials/tutorial-compiler#150]
When executing the localBuildRun scripts twice without deleting the build directory, then the tutorials repository folder is created twice in build/playbooks.
On another execution, errors are logged in the terminal (localBuildRun.sh; powershell script not tested):
`cp: cannot create regular file 'build/playbooks/tutorials/.git/objects/f6/7e0b3c7c626986e017b7e15bf7a065175244a1': Permission denied`

Actually the folder can be deleted completely before if existing

**Comment by EduardKrieger** [comment]
[https://github.com/EduardKrieger/tutorial-compiler/tree/executeFile](url)
localBuildRun is checking for existing of build folder and removing it

**Comment by maybeec** [comment]
Better would be cleaning up after execution, what do you think?
