### ISSUE TITLE
New parameter for syntax checking

### ISSUE THREAD

**Issue by GuentherJulian** [devonfw-tutorials/tutorial-compiler#221]
It would be nice to add comments in the tutorials pull request when there are syntax errors in the tutorials.

For this we need to have a new paramter we can pass to the tutorial-compiler. If the parameter is set the compiler has to store the detailed error message somewhere. In addition, we then need to modify the pipeline in the tutorials repository to read this information and comment it directly into the pull request.

**Comment by denise-khuu** [comment]
Also add to the comment, if an environment is incomplete, the missing function

**Comment by MarcelDiessner** [comment]
@GuentherJulian @denise-khuu Why do we need to define a new parameter? Are there cases where this behavior is not needed? It would be easier, if it will always comment syntax errors.

**Comment by MarcelDiessner** [comment]
What informations should the error message include besides the the missing functions?
