### ISSUE TITLE
Proper logs for tests

### ISSUE THREAD

**Issue by maybeec** [devonfw-tutorials/tutorial-compiler#228]
If we have issues like that: https://github.com/devonfw-tutorials/katacoda-scenarios/runs/2453396015?check_suite_focus=true we currently are not able to see what actually gone wrong.

It would be good, if we could be able to provide a debug parameter, which will stream also the output of the processes to the log like for example the installation log of the devonfw ide. 

It's really critical to get this done on a short term, such that we will be able to react on a short term to bugs.

**Comment by GuentherJulian** [comment]
A debug parameter is just being implemented in connection with this issue https://github.com/devonfw-tutorials/tutorial-compiler/issues/219
