### ISSUE TITLE
enhancement: executeCommand 

### ISSUE THREAD

**Issue by denise-khuu** [devonfw-tutorials/tutorial-compiler#279]
Add a function assertFileExist(), which gets a path relative to workspace to check if a certain file exist.

**Comment by GuentherJulian** [comment]
Can this issue be closed @denise-khuu? I think there is an assertion to check if a file exists now https://github.com/devonfw-tutorials/tutorial-compiler/blob/main/assertions/fileExist.ts

**Comment by denisekhuu** [comment]
I think so
