### ISSUE TITLE
Bug: restoreDevonfwIde 

### ISSUE THREAD

**Issue by denise-khuu** [devonfw-tutorials/tutorial-compiler#332]
There is a bug in this tutorial on katacoda.
It somehow doesn't restore the IDE or starts any setup file. 

https://katacoda.com/devonfw/scenarios/angular-mock-service

**Comment by GuentherJulian** [comment]
The background script does not install the devonfw-ide at the startup of the tutorial. Maybe because of the parameter that are passed to the command. This has to be investigated. Maybe by trying to install the ide with the same parameters locally.

**Comment by GuentherJulian** [comment]
Fixed with downgrade to a older ubuntu image #335.
Created a new task to investigate the problem #336.
